# 主配置文件
spring:
  # 环境配置
  profiles:
    active: dev
  # 缓存配置
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s
# mybatis-plus 配置
mybatis-plus:
  # 日志配置
  config-location: classpath:/mybatis-plus-config.xml